name: Sync Labels

on:
  push:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          yaml-file: .github/labels.yml
          skip-delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

